name: hew
description: Simple state management library for Dart and Flutter, inspired by Bloc and Riverpod.
version: 0.0.1
homepage: https://github.com/festelo/hew

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
    
  meta: ^1.8.0
  rxdart: ^0.27.7

dev_dependencies: 
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  mockito: ^5.3.2
  test: ^1.21.3
